def patternCount (text,pattern):
    count = 0
    length = 1+len(text)-len(pattern)
    for i in range (0,length):
        if text[i:(i+len(pattern))] == pattern:
            count = count+1
    return count

#1B
def frequentWords (text,k):
    frequentPatterns = []
    count = []
    for i in range (0,len(text)-k):
        pattern = text[i:(i+k)]
        value = patternCount(text,pattern)
        count.append(value)
    
    maxCount = max(count)
    for i in range (0,len(text)-k):
        if count[i] == maxCount:
            frequentPatterns.append(text[i:(i+k)])
    frequentPatterns = set(frequentPatterns)
    frequentPatterns = list(frequentPatterns)
    
    frequentPatternsString = ' '.join(frequentPatterns)
    return frequentPatternsString

print (frequentWords("AGATGAGGAAGTTGCCGAGCTCTCATGCTCGAACGTCAATTATTTGTTAAGTTGCCGAAAGTTGCCGAGCTCTCATGCAGATGAGGATTATTTGTTTCGAACGTCATCGAACGTCAAGATGAGGAGATGAGGAGATGAGGAAGTTGCCGAGCTCTCATGCATTATTTGTTATTATTTGTTATTATTTGTTAGATGAGGAAGTTGCCGAGCTCTCATGCAGATGAGGATTATTTGTTGCTCTCATGCTCGAACGTCAAAGTTGCCGAGCTCTCATGCAGATGAGGAAGTTGCCGAGCTCTCATGCAAGTTGCCGATCGAACGTCAAGATGAGGGCTCTCATGCAAGTTGCCGAAGATGAGGGCTCTCATGCTCGAACGTCATCGAACGTCAATTATTTGTTTCGAACGTCAGCTCTCATGCAAGTTGCCGATCGAACGTCATCGAACGTCAAGATGAGGAGATGAGGGCTCTCATGCATTATTTGTTAGATGAGGATTATTTGTTGCTCTCATGCGCTCTCATGCATTATTTGTTTCGAACGTCAGCTCTCATGCGCTCTCATGCTCGAACGTCATCGAACGTCAAGATGAGGTCGAACGTCAAAGTTGCCGAAAGTTGCCGATCGAACGTCAAAGTTGCCGAAAGTTGCCGAATTATTTGTTAAGTTGCCGAATTATTTGTTATTATTTGTTGCTCTCATGCATTATTTGTTAGATGAGGGCTCTCATGCATTATTTGTTAAGTTGCCGATCGAACGTCAAAGTTGCCGAGCTCTCATGCTCGAACGTCAAAGTTGCCGAGCTCTCATGCTCGAACGTCATCGAACGTCAATTATTTGTTATTATTTGTTTCGAACGTCAGCTCTCATGCATTATTTGTTGCTCTCATGCATTATTTGTTGCTCTCATGCATTATTTGTTGCTCTCATGCATTATTTGTTAAGTTGCCGATCGAACGTCAGCTCTCATGCGCTCTCATGC",12))